### ISSUE TITLE
A typo in repo's description

### ISSUE THREAD

**Issue by farooqkz** [mostafaasadi/retwitgram#1]
an extra 'b' is there!

**Comment by mostafaasadi** [comment]
باتشکر ، در کامیت   767afbd تصحیح شد

**Comment by farooqkz** [comment]
You have forgot the short description of the repo(It's not in README.md).

![scrnshot](https://user-images.githubusercontent.com/15038218/31545123-f22cd5c4-b02a-11e7-8c53-19cf9fac582d.png)

**Comment by mostafaasadi** [comment]
oh my god ! thank you

**Comment by farooqkz** [comment]
So I close this(as you have fixed that)
